version: 2.1

executors:
  main_executor:
    docker: # run the steps with Docker
      - image: maven

jobs:
  validate:
    executor: main_executor
    steps:
      - checkout
      - run: find . -name 'pom.xml' | sort | xargs cat > aux.xml
      - restore_cache:
          keys:
            - circleci-java-spring-hexa-{{ .Branch }}-{{ checksum "aux.xml" }}
            - circleci-java-spring-hexa-{{ .Branch }}-
            - circleci-java-spring-hexa-
      - run:
          name: Validation and style test checkstyle (Google stylesheets)
          command: mvn validate
      - persist_to_workspace:
          root: ~/
          paths:
            - project/
            - .m2
  tests:
    executor: main_executor
    steps:
      - attach_workspace:
          at: ~/
      - run: cd project
      - run:
          name: Test analysis
          command: mvn test
      - run:
          name: Save tests results
          command: |
            mkdir -p tests_results/unit
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp --parents {} ~/tests_results/unit \;
      - store_test_results:
          path: tests_results
      - persist_to_workspace:
          root: ~/
          paths:
            - project/
            - .m2
  compile:
    executor: main_executor
    steps:
      - attach_workspace:
          at: ~/
      - run: cd project
      - run:
          name: Project compilation
          command: mvn compile
      - persist_to_workspace:
          root: ~/
          paths:
            - project/
            - .m2
  package:
    executor: main_executor
    steps:
      - attach_workspace:
          at: ~/
      - run: cd project
      - run: mvn package dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-java-spring-hexa-{{ .Branch }}-{{ checksum "aux.xml" }}
      - persist_to_workspace:
          root: ~/
          paths:
            - project/
            - .m2

  verify:
    executor: main_executor
    steps:
      - attach_workspace:
          at: ~/
      - run: cd project
      - run:
          name: Verification (including spotbugs)
          command: mvn verify
      - run:
          name: Save checkstyle results
          command: |
            mkdir check_results
            find . -type f -regex ".*/target/checkstyle-result.xml" -not -path "./check_results/*" -exec cp --parents {} check_results/ \;
      - run:
          name: Save spotbugs results
          command: find . -type f -regex ".*/target/spotbugsXml.xml" -not -path "./check_results/*" -exec cp --parents {} check_results/ \;
      - run:
          name: Package tests
          command: tar -cvzf results.tar.gz check_results
      - store_artifacts:
          path: results.tar.gz
          destination: results.tar.gz
      - persist_to_workspace:
          root: ~/
          paths:
            - project/
            - .m2

  deploy:
    executor: main_executor
    steps:
      - attach_workspace:
          at: ~/
      - run: cd project
      - run:
           name: Creates the directory for the deploying (test)
           command: mkdir deploy
      - run:
          name: Copies the final package to the remote repository (test)
          command: mvn deploy

workflows:
  general:
    jobs:
      - validate
      - compile:
          requires:
            - validate
      - tests:
          requires:
            - compile
      - package:
          requires:
            - tests
      - verify:
          requires:
            - package
      - deploy:
          requires:
            - verify
          filters:
            branches:
              only:
                - master