version: 2.1

executors:
  main_executor:
    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-stretch

jobs:
  install:
    executor:

  validate:
    executor: main_executor
    steps:
      - checkout
      - run:
          name: Validation and style test checkstyle (Google stylesheets)
          command: mvn validate
      - persist_to_workspace:
          root: .
          paths:
            - .
  tests:
    executor: main_executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Bug analysis with spotbugs plugin (because there is no tests)
          command: mvn test
      - persist_to_workspace:
          root: .
          paths:
            - .
  compile:
    executor: main_executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Project compilation
          command: mvn compile
      - persist_to_workspace:
          root: .
          paths:
            - .
  package:
    executor: main_executor
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          key: circleci-java-spring-hexa-{{ cat `find "$(pwd)" -name pom.xml` | checksum }}

      - run: mvn compile dependency:go-offline # gets the project dependencies

      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: circleci-java-spring-hexa-{{ cat `find "$(pwd)" -name pom.xml` | checksum }}
      - run: mvn package
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    executor: main_executor
    steps:
      - attach_workspace:
          at: .
      - run:
           name: Creates the directory for the deploying
           command: mkdir deploy
      - run:
          name: Copies the final package to the remote repository
          command: mvn deploy

workflows:
  general:
    jobs:
      - validate
      - compile:
          requires:
            - validate
      - tests:
          requires:
            - compile
      - package:
          requires:
            - tests
      - deploy:
          requires:
            - package