version: 2.1

executors:
  main_executor:
    docker: # run the steps with Docker
      - image: maven

jobs:
  validate:
    executor: main_executor
    steps:
      - checkout
      - run:
          name: Validation and style test checkstyle (Google stylesheets)
          command: mvn validate
      - run:
          name: Save checkstyle results
          command: |
            mkdir checkstyle_results
            find . -type f -regex ".*/target/checkstyle-result.xml" -exec cp --parents {} checkstyle_results/ \;
      - store_artifacts:
          path: checkstyle_results
          destination: checkstyle_results
      - persist_to_workspace:
          root: .
          paths:
            - .
  tests:
    executor: main_executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test analysis
          command: mvn test
      - run:
          name: Save tests results
          command: |
            mkdir -p tests_results/unit
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp --parents {} ~/tests_results/unit \;
      - store_test_results:
          path: tests_results
      - persist_to_workspace:
          root: .
          paths:
            - .
  compile:
    executor: main_executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Project compilation
          command: mvn compile
      - persist_to_workspace:
          root: .
          paths:
            - .
  package:
    executor: main_executor
    steps:
      - attach_workspace:
          at: .
      - run: find . -name 'pom.xml' | sort | xargs cat > ~/aux.xml
      - restore_cache:
          keys:
            - circleci-java-spring-hexa-{{ checksum "~/aux.xml" }}
            - circleci-java-spring-hexa-

      - run: mvn package dependency:go-offline # gets the project dependencies

      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: circleci-java-spring-hexa-{{ checksum "~/aux.xml" }}
      - persist_to_workspace:
          root: .
          paths:
            - .

  verify:
    executor: main_executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Verification (including spotbugs)
          command: mvn verify
      - run:
          name: Save spotbugs check results
          command: |
            mkdir spotbugs_results
            find . -type f -regex ".*/target/spotbugsXml.xml" -exec cp --parents {} spotbugs_results/ \;
      - store_artifacts:
          path: spotbugs_results
          destination: spotbugs_results
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    executor: main_executor
    steps:
      - attach_workspace:
          at: .
      - run:
           name: Creates the directory for the deploying
           command: mkdir deploy
      - run:
          name: Copies the final package to the remote repository
          command: mvn deploy

workflows:
  general:
    jobs:
      - validate
      - compile:
          requires:
            - validate
      - tests:
          requires:
            - compile
      - package:
          requires:
            - tests
      - verify:
          requires:
            - package
      - deploy:
          requires:
            - verify
          filters:
            branches:
              only:
                - master